In [1]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline
import matplotlib.pyplot as plt

In [16]:
titanic = pd.read_csv("titanic.csv")
titanic

Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0    7.2500    0      1     0       0       0       0   
1               2  38.0   71.2833    1      1     0       0       0       0   
2               3  26.0    7.9250    1      0     0       0       0       0   
3               4  35.0   53.1000    1      1     0       0       0       0   
4               5  35.0    8.0500    0      0     0       0       0       0   
...           ...   ...       ...  ...    ...   ...     ...     ...     ...   
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0          0  ...        0        0        0       3        0        0   
1          0  ...        0        0        0       1        0        0   
2          0  ...        0        0        0       3        0        0   
3          0  ...        0        0        0       1        0        0   
4          0  ...        0        0        0       3        0        0   
...      ...  ...      ...      ...      ...     ...      ...      ...   
1304       0  ...        0        0        0       3        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  survived  
0          2.0        0        0         0  
1          0.0        0        0         1  
2          2.0        0        0         1  
3          2.0        0        0         1  
4          2.0        0        0         0  
...        ...      ...      ...       ...  
1304       2.0        0        0         0  
1305       0.0        0        0         0  
1306       2.0        0        0         0  
1307       2.0        0        0         0  
1308       0.0        0        0         0  

[1309 rows x 28 columns]

In [18]:
titanic.dropna(inplace=True)

<ipython-input-18-0e9622e1a85c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titanic.dropna(inplace=True)


In [19]:
titanic = titanic[['Age','Fare','Sex','Pclass','sibsp','Embarked','survived']]
titanic

Age      Fare  Sex  Pclass  sibsp  Embarked  survived
0     22.0    7.2500    0       3      1       2.0         0
1     38.0   71.2833    1       1      1       0.0         1
2     26.0    7.9250    1       3      0       2.0         1
3     35.0   53.1000    1       1      1       2.0         1
4     35.0    8.0500    0       3      0       2.0         0
...    ...       ...  ...     ...    ...       ...       ...
1304  28.0    8.0500    0       3      0       2.0         0
1305  39.0  108.9000    1       1      0       0.0         0
1306  38.5    7.2500    0       3      0       2.0         0
1307  28.0    8.0500    0       3      0       2.0         0
1308  28.0   22.3583    0       3      1       0.0         0

[1307 rows x 7 columns]

In [20]:
titanic.shape

(1307, 7)

In [21]:
X = np.asarray(titanic[['Age','Fare','Sex','Pclass','sibsp','Embarked']])
X[0:10]

array([[22.    ,  7.25  ,  0.    ,  3.    ,  1.    ,  2.    ],
       [38.    , 71.2833,  1.    ,  1.    ,  1.    ,  0.    ],
       [26.    ,  7.925 ,  1.    ,  3.    ,  0.    ,  2.    ],
       [35.    , 53.1   ,  1.    ,  1.    ,  1.    ,  2.    ],
       [35.    ,  8.05  ,  0.    ,  3.    ,  0.    ,  2.    ],
       [28.    ,  8.4583,  0.    ,  3.    ,  0.    ,  1.    ],
       [54.    , 51.8625,  0.    ,  1.    ,  0.    ,  2.    ],
       [ 2.    , 21.075 ,  0.    ,  3.    ,  3.    ,  2.    ],
       [27.    , 11.1333,  1.    ,  3.    ,  0.    ,  2.    ],
       [14.    , 30.0708,  1.    ,  2.    ,  1.    ,  0.    ]])

In [22]:
y = np.asarray(titanic['survived'])
y[0:10]

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1], dtype=int64)

In [23]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-0.58026066, -0.50183865, -0.74189971,  0.84044746,  0.48027176,
         0.62293984],
       [ 0.66229729,  0.7360229 ,  1.34789107, -1.55011801,  0.48027176,
        -1.83311559],
       [-0.26962117, -0.48878987,  1.34789107,  0.84044746, -0.47953739,
         0.62293984],
       [ 0.42931768,  0.38451192,  1.34789107, -1.55011801,  0.48027176,
         0.62293984],
       [ 0.42931768, -0.48637343, -0.74189971,  0.84044746, -0.47953739,
         0.62293984]])

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=4)
print ('Train set:', X_train.shape, y_train.shape)
print ('Test set:', X_test.shape, y_test.shape)

Train set: (914, 6) (914,)
Test set: (393, 6) (393,)


In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [32]:
y_hat=LR.predict(X_test)
y_hat

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,

In [38]:
from sklearn.metrics import classification_report,confusion_matrix
cnf_matrix = confusion_matrix(y_test, y_hat, labels=[1,0])
np.set_printoptions(precision=2)
print(cnf_matrix)
print(classification_report(y_test,y_hat))


[[ 31  76]
 [ 18 268]]
              precision    recall  f1-score   support

           0       0.78      0.94      0.85       286
           1       0.63      0.29      0.40       107

    accuracy                           0.76       393
   macro avg       0.71      0.61      0.62       393
weighted avg       0.74      0.76      0.73       393



In [40]:
yhat_prob = LR.predict_proba(X_test)
from sklearn.metrics import log_loss
log_loss(y_test,yhat_prob)

0.5096865391553749